### ISSUE TITLE
録音開始ボタンを連打するとクラッシュする

### ISSUE THREAD

**Issue by diffserve** [diffserve/techbowl_mission_Radiotalk#7]
「エラー内容」
2021-03-12 11:05:00.931 29874-29874/com.ym.talk_app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ym.talk_app, PID: 29874
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.ym.talk_app.ui.fragments.recipes.bottomsheet.RecipesBottomSheet.onRequestPermissionsResult(RecipesBottomSheet.kt:176)
        at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:768)
        at android.app.Activity.requestPermissions(Activity.java:5149)
        at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
        at androidx.fragment.app.FragmentActivity.requestPermissionsFromFragment(FragmentActivity.java:860)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onRequestPermissionsFromFragment(FragmentActivity.java:947)
        at androidx.fragment.app.Fragment.requestPermissions(Fragment.java:1390)
        at com.ym.talk_app.ui.fragments.recipes.bottomsheet.RecipesBottomSheet$onCreateView$4.onClick(RecipesBottomSheet.kt:103)
        at android.view.View.performClick(View.java:7184)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7161)
        at android.view.View.access$3500(View.java:818)
        at android.view.View$PerformClick.run(View.java:27677)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

「エラー原因」
　　permissionの要求結果が帰る前に、onRequestPermissionResult()が開始してしまっているため、
　　grantResults: IntArray　に何も格納されていない。
　　にも拘らず、0番目の要素にアクセスしているため、ArrayIndexOutOfBoundsException発生。
　　(googleのガイドに沿ったコードでエラー発生する)

**Comment by diffserve** [comment]
Pull request #13にて解決
